version: '3.4'

services:
  testweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  testadmin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

