version: '3.4'

services:
  testweb:
    image: ${DOCKER_REGISTRY-}testweb
    build:
      context: .
      dockerfile: TestWeb/Dockerfile
    port: "8044:80"
  testadmin:
    image: ${DOCKER_REGISTRY-}testadmin
    build:
      context: .
      dockerfile: TestAdmin/Dockerfile
  port: "8045:80"
