version: '3.4'

services:
  testweb:
    image: ${DOCKER_REGISTRY-}testweb   
    build:  
      context: .  
      dockerfile: TestWeb/Dockerfile  
    ports:  
    - 8044:80 
    container_name: netcore_testweb  
    deploy:
      restart_policy:  
        condition: on-failure
        delay: 5s
        max_attempts: 3 
  testadmin:
    image: ${DOCKER_REGISTRY-}testadmin  
    build:  
      context: . 
      dockerfile: TestAdmin/Dockerfile 
    ports:  
    - 8045:80 
    container_name: netcore_testadmin 
    deploy:
      restart_policy: 
        condition: on-failure
        delay: 5s
        max_attempts: 3
 