version: '3.4'

services:
  testweb:
    image: ${DOCKER_REGISTRY-}testweb
    build:
      context: .
      dockerfile: TestWeb/Dockerfile
    ports: -"8044:80"
  testadmin:
    image: ${DOCKER_REGISTRY-}testadmin
    build:
      context: .
      dockerfile: TestAdmin/Dockerfile
    ports: -"8045:80"
